apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ad-service
  template:
    metadata:
      labels:
        app: ad-service
    spec:
      containers:
        - name: ad-service
          image: sreenathsvrm/ad-tracking-system-ad-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ad-service-config
            - secretRef:
                name: ad-service-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5